lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # and token for socket
    plug(AppWeb.Auth.SetCurrentUserPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", AppWeb do
    # Use the default browser stack
    pipe_through(:browser)

    resources("/users", UserController)
    resources("/rooms", RoomController)

    get("/register", Auth.RegistrationController, :new)
    post("/register", Auth.RegistrationController, :create)

    get("/signin", Auth.SessionController, :new)
    post("/signin", Auth.SessionController, :create)
    delete("/signout", Auth.SessionController, :delete)

    get("/contact", Auth.ContactController, :new)
    post("/contact", Auth.ContactController, :create)

    get("/", PageController, :index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end
end

lib/app_web/views/layout_view.ex
defmodule AppWeb.LayoutView do
  use AppWeb, :view

  def js_view_name(module, template) do
    (to_string(module) <> "_" <> to_string(template))
    |> to_string
    |> String.replace("View", "")
    |> String.replace(".html", "")
    |> String.downcase()
    |> String.split(".")
    |> Enum.slice(-1, 1)
    |> to_string
  end
end

lib/app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Test!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@view_module, @view_template) %>">
    <div class="container">
      <header class="header">
       <nav no_class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <span><strong>
          <%= link "Logo", to: page_path(@conn, :index), style: "text-decoration:none; color:black" %>
          </strong></span>
          <%= link "| Contact", to: contact_path(@conn, :new)%>
          <%= link "| Users", to: user_path(@conn, :index)%>
          <%= link "| Rooms", to: room_path(@conn, :index)%>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= if @user_signed_in? do %>
            <span> Hi,<%= @current_user.name %></span>
            <%= link "Sign out", to: session_path(@conn, :delete), method: :delete%>
          <% else %>
            <%= link "Register", to: registration_path(@conn, :new) %>
            or
            <%= link "Signin", to: session_path(@conn, :new)%>
          <% end %>
        </ul>
      </nav>
      <br/>
      <small><small><%= js_view_name(@view_module, @view_template) %></small></small>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>